name: Merge to Master

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    name: Publish version to pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/poetry-aws-sam/
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.02'
      - name: Ensure pip is latest version
        run: python -m pip install -U pip
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Set poetry virtual env
        run: poetry install --with dev --sync
      - name: Poetry build dist
        run: poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  tag:
    name: Tag release with a git tag
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.1
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10'
      - name: Ensure pip is latest version
        run: python -m pip install -U pip
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Set poetry virtual env
        run: poetry install --with dev --sync
      - name: Tag release
        run: |
          VERSION=v$(poetry version --short)
          git tag $VERSION
          git push origin $VERSION
