name: Merge to Master

on:
  push:
    branches:
      - 'master'

jobs:
  lint-format-test:
    uses: ./.github/workflows/format_lint_test.yml
  publish:
    name: Publish version to pypi
    runs-on: ubuntu-latest
    needs: lint-format-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.1
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
      - name: Ensure pip is latest version
        run: python -m pip install -U pip
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Set poetry virtual env
        run: poetry install --with dev --sync
      - name: Publish package to pypi
        run: poetry publish --build -r test-pypi
      - name: Tag release
        run: |
          VERSION=v$(poetry version --short)
          git tag $VERSION
          git push origin $VERSION

